---
- name: Installation, Docker Flask and Docker Nginx
  hosts: localhost
  become: yes

  tasks:
 
    - name: Create Directory for projects
      file: path=/opt/docker state=directory
    - name: Copy NGINX docker 
      copy:
        src: ../nginx
        dest: /opt/docker 
        mode: 0755
        owner: root
        group: root
    - name: Build Nginx Docker container 
      community.docker.docker_image:
        build: 
          path: /opt/docker/nginx
        name: nginx
        tag: v2
        source: build
    - name: Copy Flask docker 
      copy:
        src: ../webapp
        dest: /opt/docker 
        mode: 0755
        owner: root
        group: root
    - name: Build Flask Docker container 
      community.docker.docker_image:
        build: 
          path: /opt/docker/webapp
        name: flask
        tag: v1
        source: build
