name: CI

on:
  push:
    branches: [ main ]
jobs:

  build:

    runs-on: self-hosted
    env:
      VERSION: 0.4
    steps:
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: bash
        run: |
          cd /home/banlex/final
          git pull
          #ansible-playbook test.yml
          cd ./nginx
          #export VERSION=git describe --long
          sudo docker build -t nginx:$VERSION .
          cd ../webapp
          sudo docker build -t webapp:$VERSION .


