name: Docker Image CI
##
on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
 #   - name: Install SSH key
 #     uses: shimataro/ssh-key-action@v2
 #     with:
 #       key: ${{ secrets.SSH_KEY }}
 #       name: id_rsa # optional
 #       known_hosts: ${{ secrets.KNOWN_HOSTS }}
 #       config: ${{ secrets.CONFIG }} # ssh_config; optional
 #       if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
  
    # Steps represent a sequence of tasks that will be executed as part of the job
#sudo apt-get update -y
#sudo apt install software-properties-common -y
#sudo add-apt-repository --yes --update ppa:ansible/ansible -y
#sudo apt-get install -y git ansible  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run a one-line script
      shell: bash
      run: |
 #       python -V
 #       sudo apt-get update -y
 #       sudo apt install software-properties-common -y
 #       sudo add-apt-repository --yes --update ppa:ansible/ansible -y
 #       sudo apt-get install -y git ansible
        ansible-playbook -vvv -i ./playbooks/hosts.ini ./playbooks/docker-image.yml
