name: Docker Image CI

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    #- uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file webapp/Dockerfile --tag my-image-name:$(date +%s)
